# Generated by Django 5.0.7 on 2024-08-31 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoomapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthtoken',
            name='user',
        ),
    ]
